# Generated by Django 4.1.4 on 2022-12-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('experience', models.FloatField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('call_video', models.BooleanField(default=False)),
                ('call_email', models.BooleanField(default=False)),
                ('call_text', models.BooleanField(default=False)),
            ],
        ),
    ]
